import type { TraderTemplate } from './types'

export const publicTraderTemplates: TraderTemplate[] = [
  {
    id: 'berkshire-hathaway',
    name: 'Berkshire Hathaway',
    operator: 'Warren Buffett / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Concentrated quality value',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Track disclosed U.S. long-equity position changes as a slow portfolio-research signal.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1067983/000119312526226661/0001193125-26-226661-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
    winRatePct: 82,
    totalReturn30d: 4.8,
    activePositions: [
      { assetSymbol: 'AAPL', assetName: 'Apple Inc.', direction: 'LONG', allocationPct: 28.4, entryPriceUsd: 178.5, currentPriceUsd: 224.3, pnlPct: 25.6 },
      { assetSymbol: 'BAC', assetName: 'Bank of America', direction: 'LONG', allocationPct: 11.2, entryPriceUsd: 32.1, currentPriceUsd: 39.8, pnlPct: 24.0 },
      { assetSymbol: 'AXP', assetName: 'American Express', direction: 'LONG', allocationPct: 10.8, entryPriceUsd: 215.4, currentPriceUsd: 268.9, pnlPct: 24.8 },
      { assetSymbol: 'KO', assetName: 'Coca-Cola Co.', direction: 'LONG', allocationPct: 8.5, entryPriceUsd: 59.2, currentPriceUsd: 68.4, pnlPct: 15.5 },
      { assetSymbol: 'OXY', assetName: 'Occidental Pet.', direction: 'ACCUMULATE', allocationPct: 5.1, entryPriceUsd: 58.9, currentPriceUsd: 64.2, pnlPct: 9.0 },
    ],
    assetAllocation: [
      { name: 'Tech / Consumer', percentage: 42, color: '#3b82f6' },
      { name: 'Financials', percentage: 32, color: '#10b981' },
      { name: 'Energy', percentage: 16, color: '#f59e0b' },
      { name: 'Cash Reserve', percentage: 10, color: '#64748b' },
    ],
    performanceCurve: [
      { date: 'Day 1', returnPct: 0.0 },
      { date: 'Day 7', returnPct: 1.2 },
      { date: 'Day 14', returnPct: 2.1 },
      { date: 'Day 21', returnPct: 3.5 },
      { date: 'Day 30', returnPct: 4.8 },
    ],
  },
  {
    id: 'pershing-square',
    name: 'Pershing Square',
    operator: 'Bill Ackman / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Concentrated activist equity',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Observe concentrated public-equity disclosures and position changes, not intraday trades.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1336528/000117266126002336/0001172661-26-002336-index.html',
    sourceLabel: 'SEC 13F / Q1 2026',
    winRatePct: 79,
    totalReturn30d: 8.2,
    activePositions: [
      { assetSymbol: 'QSR', assetName: 'Restaurant Brands', direction: 'LONG', allocationPct: 22.0, entryPriceUsd: 68.4, currentPriceUsd: 79.1, pnlPct: 15.6 },
      { assetSymbol: 'HLT', assetName: 'Hilton Worldwide', direction: 'LONG', allocationPct: 18.5, entryPriceUsd: 184.2, currentPriceUsd: 228.6, pnlPct: 24.1 },
      { assetSymbol: 'CMG', assetName: 'Chipotle Mexican Grill', direction: 'LONG', allocationPct: 16.2, entryPriceUsd: 52.1, currentPriceUsd: 64.8, pnlPct: 24.3 },
      { assetSymbol: 'GOOGL', assetName: 'Alphabet Inc.', direction: 'ACCUMULATE', allocationPct: 14.8, entryPriceUsd: 142.3, currentPriceUsd: 178.9, pnlPct: 25.7 },
    ],
    assetAllocation: [
      { name: 'Consumer & Retail', percentage: 56.7, color: '#8b5cf6' },
      { name: 'Big Tech', percentage: 14.8, color: '#06b6d4' },
      { name: 'Media / Ent.', percentage: 12.1, color: '#ec4899' },
      { name: 'Cash Reserve', percentage: 16.4, color: '#64748b' },
    ],
    performanceCurve: [
      { date: 'Day 1', returnPct: 0.0 },
      { date: 'Day 7', returnPct: 2.4 },
      { date: 'Day 14', returnPct: 4.1 },
      { date: 'Day 21', returnPct: 6.8 },
      { date: 'Day 30', returnPct: 8.2 },
    ],
  },
  {
    id: 'duquesne-family-office',
    name: 'Duquesne Family Office',
    operator: 'Stanley Druckenmiller / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Macro-aware growth and rotation',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Use disclosed long-equity rotation as one input to a broader macro thesis.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1536411/000153641126000004/0001536411-26-000004-index-headers.html',
    sourceLabel: 'SEC 13F / Q1 2026',
    winRatePct: 85,
    totalReturn30d: 12.4,
    activePositions: [
      { assetSymbol: 'NVDA', assetName: 'NVIDIA Corp.', direction: 'LONG', allocationPct: 24.5, entryPriceUsd: 98.4, currentPriceUsd: 132.8, pnlPct: 34.9 },
      { assetSymbol: 'MSFT', assetName: 'Microsoft Corp.', direction: 'LONG', allocationPct: 18.2, entryPriceUsd: 388.1, currentPriceUsd: 445.2, pnlPct: 14.7 },
      { assetSymbol: 'CEG', assetName: 'Constellation Energy', direction: 'ACCUMULATE', allocationPct: 12.6, entryPriceUsd: 195.4, currentPriceUsd: 242.1, pnlPct: 23.9 },
    ],
    assetAllocation: [
      { name: 'AI Hardware / Tech', percentage: 42.7, color: '#10b981' },
      { name: 'Clean Energy Power', percentage: 22.6, color: '#f59e0b' },
      { name: 'SaaS Infrastructure', percentage: 18.2, color: '#3b82f6' },
      { name: 'Cash / Derivatives', percentage: 16.5, color: '#64748b' },
    ],
    performanceCurve: [
      { date: 'Day 1', returnPct: 0.0 },
      { date: 'Day 7', returnPct: 3.1 },
      { date: 'Day 14', returnPct: 6.4 },
      { date: 'Day 21', returnPct: 9.8 },
      { date: 'Day 30', returnPct: 12.4 },
    ],
  },
  {
    id: 'hyperliquid-4e23',
    name: 'HL 0x4e23...20c3',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'High-volume perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Observe positions and performance for a high-volume public account. Identity is not asserted.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0x4e23288cee4960f9f962195c22948e4bc7ae20c3',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0x4e23288cee4960f9f962195c22948e4bc7ae20c3',
    snapshot: 'Current active-wallet cohort',
    winRatePct: 76,
    totalReturn30d: 34.6,
    activePositions: [
      { assetSymbol: 'BTC-PERP', assetName: 'Bitcoin 50x Perps', direction: 'LONG', allocationPct: 45.0, entryPriceUsd: 62400, currentPriceUsd: 68900, pnlPct: 52.1 },
      { assetSymbol: 'ETH-PERP', assetName: 'Ethereum 25x Perps', direction: 'LONG', allocationPct: 30.0, entryPriceUsd: 3150, currentPriceUsd: 3568, pnlPct: 33.1 },
      { assetSymbol: 'SOL-PERP', assetName: 'Solana 20x Perps', direction: 'LONG', allocationPct: 15.0, entryPriceUsd: 132.5, currentPriceUsd: 158.4, pnlPct: 39.0 },
    ],
    assetAllocation: [
      { name: 'BTC Perps (50x)', percentage: 45, color: '#f7931a' },
      { name: 'ETH Perps (25x)', percentage: 30, color: '#627eea' },
      { name: 'SOL Perps (20x)', percentage: 15, color: '#14f195' },
      { name: 'Margin USDC', percentage: 10, color: '#2775ca' },
    ],
    performanceCurve: [
      { date: 'Day 1', returnPct: 0.0 },
      { date: 'Day 7', returnPct: 8.5 },
      { date: 'Day 14', returnPct: 16.2 },
      { date: 'Day 21', returnPct: 24.8 },
      { date: 'Day 30', returnPct: 34.6 },
    ],
  },
  {
    id: 'polymarket-swisstony',
    name: 'swisstony',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile. Follow positions as research, not guaranteed edge.',
    sourceUrl: 'https://polymarket.com/profile/0x204f72f35326db932158cba6adff0b9a1da95e14',
    sourceLabel: 'Polymarket public profile',
    identity: '0x204f72f35326db932158cba6adff0b9a1da95e14',
    snapshot: 'Monthly leaderboard cohort',
    winRatePct: 71,
    totalReturn30d: 21.8,
    activePositions: [
      { assetSymbol: 'FED-RATE-CUT', assetName: 'Fed Rate Cut 2026 (YES)', direction: 'LONG', allocationPct: 35.0, entryPriceUsd: 0.65, currentPriceUsd: 0.84, pnlPct: 29.2 },
      { assetSymbol: 'BTC-100K', assetName: 'BTC > $100K in 2026 (YES)', direction: 'LONG', allocationPct: 25.0, entryPriceUsd: 0.52, currentPriceUsd: 0.71, pnlPct: 36.5 },
      { assetSymbol: 'US-RECESSION', assetName: 'U.S. Recession in 2026 (NO)', direction: 'HOLD', allocationPct: 20.0, entryPriceUsd: 0.82, currentPriceUsd: 0.91, pnlPct: 11.0 },
      { assetSymbol: 'SOL-ETF', assetName: 'Solana ETF Approval (YES)', direction: 'ACCUMULATE', allocationPct: 10.0, entryPriceUsd: 0.38, currentPriceUsd: 0.42, pnlPct: 10.5 },
    ],
    assetAllocation: [
      { name: 'Fed Interest Rates', percentage: 35, color: '#10b981' },
      { name: 'Bitcoin Milestones', percentage: 25, color: '#3b82f6' },
      { name: 'US Macro & GDP', percentage: 20, color: '#f59e0b' },
      { name: 'Solana Ecosystem', percentage: 10, color: '#8b5cf6' },
      { name: 'Cash Reserve', percentage: 10, color: '#64748b' },
    ],
    performanceCurve: [
      { date: 'Day 1', returnPct: 0.0 },
      { date: 'Day 7', returnPct: 5.2 },
      { date: 'Day 14', returnPct: 11.8 },
      { date: 'Day 21', returnPct: 16.4 },
      { date: 'Day 30', returnPct: 21.8 },
    ],
  },
]
