import type { TraderTemplate } from './types'

export const publicTraderTemplates: TraderTemplate[] = [
  {
    id: 'berkshire-hathaway',
    name: 'Berkshire Hathaway',
    operator: 'Warren Buffett / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Concentrated quality value',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Track disclosed U.S. long-equity position changes as a slow portfolio-research signal.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1067983/000119312526226661/0001193125-26-226661-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'pershing-square',
    name: 'Pershing Square',
    operator: 'Bill Ackman / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Concentrated activist equity',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Observe concentrated public-equity disclosures and position changes, not intraday trades.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1336528/000117266126002336/0001172661-26-002336-index.html',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'duquesne-family-office',
    name: 'Duquesne Family Office',
    operator: 'Stanley Druckenmiller / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Macro-aware growth and rotation',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Use disclosed long-equity rotation as one input to a broader macro thesis.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1536411/000153641126000004/0001536411-26-000004-index-headers.html',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'appaloosa-management',
    name: 'Appaloosa Management',
    operator: 'David Tepper / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Opportunistic macro equity',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Watch position concentration and sector rotation in public long-equity disclosures.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1656456/000165645626000002/0001656456-26-000002-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'baupost-group',
    name: 'Baupost Group',
    operator: 'Seth Klarman / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Deep value and special situations',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Track disclosed U.S. long-equity holdings as a value-research watchlist.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1061768/000106176826000007/0001061768-26-000007-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'bridgewater-associates',
    name: 'Bridgewater Associates',
    operator: 'Bridgewater investment organization',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Systematic global macro observer',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Observe the firm filing as a partial U.S. equity lens, not a complete macro book.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1350694/000135069426000002/0001350694-26-000002-index.html',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'soros-fund-management',
    name: 'Soros Fund Management',
    operator: 'Soros Fund Management team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Macro and event-driven equity observer',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Follow the current firm filing without attributing every position to George Soros personally.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1029160/000090266426002529/0000902664-26-002529-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'elliott-investment-management',
    name: 'Elliott Investment Management',
    operator: 'Paul Singer / investment team',
    market: 'traditional',
    sourceKind: 'sec-13f',
    verification: 'SEC FILED',
    strategy: 'Activist and special situations',
    cadence: 'Quarterly filing changes',
    delay: 'Up to 45 days',
    description: 'Watch concentrated public holdings and pair the data with source-linked company events.',
    sourceUrl: 'https://www.sec.gov/Archives/edgar/data/1791786/000101359426000613/0001013594-26-000613-index.htm',
    sourceLabel: 'SEC 13F / Q1 2026',
  },
  {
    id: 'oaktree-howard-marks',
    name: 'Oaktree Credit Cycle',
    operator: 'Howard Marks / Oaktree',
    market: 'traditional',
    sourceKind: 'official-research',
    verification: 'OFFICIAL SOURCE',
    strategy: 'Credit cycles and risk posture',
    cadence: 'When official memos publish',
    delay: 'Research, not a trade feed',
    description: 'Extract source-linked credit, risk, and cycle claims from official Oaktree memos.',
    sourceUrl: 'https://www.oaktreecapital.com/insights',
    sourceLabel: 'Official Oaktree insights',
  },
  {
    id: 'blackrock-rick-rieder',
    name: 'BlackRock Fixed Income',
    operator: 'Rick Rieder / fixed-income team',
    market: 'traditional',
    sourceKind: 'official-research',
    verification: 'OFFICIAL SOURCE',
    strategy: 'Rates, duration, credit and income',
    cadence: 'Official outlook updates',
    delay: 'Research, not a trade feed',
    description: 'Track fixed-income regime views and portfolio themes without claiming personal live positions.',
    sourceUrl: 'https://www.blackrock.com/us/individual/insights/fixed-income-outlook',
    sourceLabel: 'Official BlackRock outlook',
  },
  {
    id: 'hyperliquid-4e23',
    name: 'HL 0x4e23...20c3',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'High-volume perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Observe positions and performance for a high-volume public account. Identity is not asserted.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0x4e23288cee4960f9f962195c22948e4bc7ae20c3',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0x4e23288cee4960f9f962195c22948e4bc7ae20c3',
    snapshot: 'Current active-wallet cohort',
  },
  {
    id: 'hyperliquid-7fba',
    name: 'HL 0x7fba...04ab',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Active perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Follow a public account selected for meaningful volume and multi-window performance data.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0x7fba7e745bd97f828c824589680749b55a8c04ab',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0x7fba7e745bd97f828c824589680749b55a8c04ab',
    snapshot: 'Current active-wallet cohort',
  },
  {
    id: 'hyperliquid-fe7c',
    name: 'HL 0xfe7c...b7ae',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Active perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Follow a public account selected for substantial activity and positive observed history.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0xfe7ce058edc7cfcde9ef8262ba51f8d4796ab7ae',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0xfe7ce058edc7cfcde9ef8262ba51f8d4796ab7ae',
    snapshot: 'Current active-wallet cohort',
  },
  {
    id: 'hyperliquid-15a4',
    name: 'HL 0x15a4...dfdb',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'High-turnover perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Observe an active public wallet across 24-hour, weekly, monthly, and all-time windows.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0x15a4f009bb324a3fb9e36137136b201e3fe0dfdb',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0x15a4f009bb324a3fb9e36137136b201e3fe0dfdb',
    snapshot: 'Current active-wallet cohort',
  },
  {
    id: 'hyperliquid-469e',
    name: 'HL 0x469e...58a5',
    operator: 'Public Hyperliquid wallet',
    market: 'crypto',
    sourceKind: 'onchain-wallet',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'High-volume perpetuals',
    cadence: 'Onchain account updates',
    delay: 'Near real time',
    description: 'Observe a high-volume public wallet with verifiable account history and no identity claim.',
    sourceUrl: 'https://dexly.trade/hyperliquid/leaderboard/0x469e9a7f624b04c24f0e64edf8d8a277e6bf58a5',
    sourceLabel: 'Hyperliquid public activity',
    identity: '0x469e9a7f624b04c24f0e64edf8d8a277e6bf58a5',
    snapshot: 'Current active-wallet cohort',
  },
  {
    id: 'polymarket-swisstony',
    name: 'swisstony',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile. Follow positions as research, not guaranteed edge.',
    sourceUrl: 'https://polymarket.com/profile/0x204f72f35326db932158cba6adff0b9a1da95e14',
    sourceLabel: 'Polymarket public profile',
    identity: '0x204f72f35326db932158cba6adff0b9a1da95e14',
    snapshot: 'Monthly leaderboard cohort',
  },
  {
    id: 'polymarket-deeddit',
    name: 'DEEDDIT',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile with source-linked positions and history.',
    sourceUrl: 'https://polymarket.com/profile/0x09b428f7c2b469786286214aa5c90dd9015f7320',
    sourceLabel: 'Polymarket public profile',
    identity: '0x09b428f7c2b469786286214aa5c90dd9015f7320',
    snapshot: 'Monthly leaderboard cohort',
  },
  {
    id: 'polymarket-asparagus2012',
    name: 'asparagus2012',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile. Performance is observed, never projected.',
    sourceUrl: 'https://polymarket.com/profile/0x476e1322d1a412fa0325527b8c3bc5e707b1396d',
    sourceLabel: 'Polymarket public profile',
    identity: '0x476e1322d1a412fa0325527b8c3bc5e707b1396d',
    snapshot: 'Monthly leaderboard cohort',
  },
  {
    id: 'polymarket-sparkling8899',
    name: 'Sparkling8899',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile with a publicly resolvable account address.',
    sourceUrl: 'https://polymarket.com/profile/0x2e25b222e2080c377fc1fb2b9f926315f0f4d49e',
    sourceLabel: 'Polymarket public profile',
    identity: '0x2e25b222e2080c377fc1fb2b9f926315f0f4d49e',
    snapshot: 'Monthly leaderboard cohort',
  },
  {
    id: 'polymarket-allezpapa',
    name: 'Allezpapa',
    operator: 'Public Polymarket profile',
    market: 'crypto',
    sourceKind: 'leaderboard-profile',
    verification: 'ONCHAIN PUBLIC',
    strategy: 'Prediction-market portfolio',
    cadence: 'Public profile updates',
    delay: 'Near real time',
    description: 'Current monthly leaderboard profile. Copying is disabled until risk controls graduate.',
    sourceUrl: 'https://polymarket.com/profile/0xe549581668a5751c1972d3ad2d1991d900bd2d54',
    sourceLabel: 'Polymarket public profile',
    identity: '0xe549581668a5751c1972d3ad2d1991d900bd2d54',
    snapshot: 'Monthly leaderboard cohort',
  },
]
